//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickRoute.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuickRoute.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Files.
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string Altitude {
            get {
                return ResourceManager.GetString("Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        public static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete lap {0}.
        /// </summary>
        public static string DeleteLapX {
            get {
                return ResourceManager.GetString("DeleteLapX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction deviation.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.matstroeng.se/doma.
        /// </summary>
        public static string DomaWebsiteUrl {
            get {
                return ResourceManager.GetString("DomaWebsiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.matstroeng.se/quickroute/en/donation.php.
        /// </summary>
        public static string DonationUrl {
            get {
                return ResourceManager.GetString("DonationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a point on the route and drag it to the corresponding location on the map. At least two points along the route, preferable well interspaced, need to be adjusted. If needed, more points can be used. Hold down Ctrl and click on an adjusted point to remove it. Right-click and drag to move the map. When adjustment is finished, select the pointer tool to display the color-coded route line..
        /// </summary>
        public static string DynamicHelp_MouseTool_AdjustRoute {
            get {
                return ResourceManager.GetString("DynamicHelp_MouseTool_AdjustRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a point on the route to remove the preceding or succeeding part of the route. Right-click and drag to move the map..
        /// </summary>
        public static string DynamicHelp_MouseTool_Cut {
            get {
                return ResourceManager.GetString("DynamicHelp_MouseTool_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a point on the route to add a split time. Hold down Ctrl and click on a split time to remove it. Hold down Shift and click the route to add a split at a specific time. Right-click and drag to move the map..
        /// </summary>
        public static string DynamicHelp_MouseTool_Lap {
            get {
                return ResourceManager.GetString("DynamicHelp_MouseTool_Lap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover the mouse pointer over the route to view current time, distance, pace etc..
        /// </summary>
        public static string DynamicHelp_MouseTool_Pointer {
            get {
                return ResourceManager.GetString("DynamicHelp_MouseTool_Pointer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the area where the map image should be enlarged..
        /// </summary>
        public static string DynamicHelp_MouseTool_ZoomIn {
            get {
                return ResourceManager.GetString("DynamicHelp_MouseTool_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the center point where the map image should be scaled down..
        /// </summary>
        public static string DynamicHelp_MouseTool_ZoomOut {
            get {
                return ResourceManager.GetString("DynamicHelp_MouseTool_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string EastAbbreviated {
            get {
                return ResourceManager.GetString("EastAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed Time.
        /// </summary>
        public static string ElapsedTime {
            get {
                return ResourceManager.GetString("ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to export image file.
        /// </summary>
        public static string Error_ExportImage {
            get {
                return ResourceManager.GetString("Error_ExportImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to export route file.
        /// </summary>
        public static string Error_ExportRoute {
            get {
                return ResourceManager.GetString("Error_ExportRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Earth does not seem to be installed on this computer. Download it from earth.google.com..
        /// </summary>
        public static string Error_GoogleEarthNotInstalledMessage {
            get {
                return ResourceManager.GetString("Error_GoogleEarthNotInstalledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Earth is not installed.
        /// </summary>
        public static string Error_GoogleEarthNotInstalledTitle {
            get {
                return ResourceManager.GetString("Error_GoogleEarthNotInstalledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is not a valid QuickRoute file..
        /// </summary>
        public static string Error_InvalidQuickRouteFile {
            get {
                return ResourceManager.GetString("Error_InvalidQuickRouteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when communicating with map publishing server.
        /// </summary>
        public static string Error_MapPublishCommunication {
            get {
                return ResourceManager.GetString("Error_MapPublishCommunication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to create a new document.
        /// </summary>
        public static string Error_NewDocument {
            get {
                return ResourceManager.GetString("Error_NewDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to open document.
        /// </summary>
        public static string Error_OpenDocument {
            get {
                return ResourceManager.GetString("Error_OpenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when trying to save document.
        /// </summary>
        public static string Error_SaveDocument {
            get {
                return ResourceManager.GetString("Error_SaveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Route To GPX.
        /// </summary>
        public static string ExportGPXTitle {
            get {
                return ResourceManager.GetString("ExportGPXTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Image.
        /// </summary>
        public static string ExportImageTitle {
            get {
                return ResourceManager.GetString("ExportImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To KMZ.
        /// </summary>
        public static string ExportKMZTitle {
            get {
                return ResourceManager.GetString("ExportKMZTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Route Data.
        /// </summary>
        public static string ExportRouteDataTitle {
            get {
                return ResourceManager.GetString("ExportRouteDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        public static string FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All QuickRoute files (*.qrt; *.xml; *.jpg; *.jpeg)|*.qrt;*.xml;*.jpg;*.jpeg.
        /// </summary>
        public static string FileFilter_AllQuickRouteFiles {
            get {
                return ResourceManager.GetString("FileFilter_AllQuickRouteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frwd text files (*.txt)|*.txt.
        /// </summary>
        public static string FileFilter_FrwdTxtFiles {
            get {
                return ResourceManager.GetString("FileFilter_FrwdTxtFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gpx (*.gpx)|*.gpx.
        /// </summary>
        public static string FileFilter_GpxFiles {
            get {
                return ResourceManager.GetString("FileFilter_GpxFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files  (*.jpg; *.jpeg; *.gif; *.png; *.tif; *.tiff)|*.jpg;*.jpeg;*.gif;*.png;*.tif;*.tiff.
        /// </summary>
        public static string FileFilter_ImageFiles {
            get {
                return ResourceManager.GetString("FileFilter_ImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg (*.jpg; *.jpeg)|*.jpg;*.jpeg.
        /// </summary>
        public static string FileFilter_JpegFiles {
            get {
                return ResourceManager.GetString("FileFilter_JpegFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg files exported from QuickRoute (*.jpg; *.jpeg)|*.jpg;*.jpeg.
        /// </summary>
        public static string FileFilter_JpegFilesExportedFromQuickRoute {
            get {
                return ResourceManager.GetString("FileFilter_JpegFilesExportedFromQuickRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kmz (*.kmz)|*.kmz.
        /// </summary>
        public static string FileFilter_KmzFiles {
            get {
                return ResourceManager.GetString("FileFilter_KmzFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navilock act files (*.act)|*.act.
        /// </summary>
        public static string FileFilter_NavilockActFiles {
            get {
                return ResourceManager.GetString("FileFilter_NavilockActFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Png (*.png)|*.png.
        /// </summary>
        public static string FileFilter_PngFiles {
            get {
                return ResourceManager.GetString("FileFilter_PngFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickRoute 1.0 xml files (*.xml)|*.xml.
        /// </summary>
        public static string FileFilter_QuickRoute10Files {
            get {
                return ResourceManager.GetString("FileFilter_QuickRoute10Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickRoute files (*.qrt)|*.qrt.
        /// </summary>
        public static string FileFilter_QuickRouteFiles {
            get {
                return ResourceManager.GetString("FileFilter_QuickRouteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route data files (*.xml)|*.xml.
        /// </summary>
        public static string FileFilter_RouteDataFiles {
            get {
                return ResourceManager.GetString("FileFilter_RouteDataFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garmin Training Center history files (*.tcx)|*.tcx.
        /// </summary>
        public static string FileFilter_TcxFiles {
            get {
                return ResourceManager.GetString("FileFilter_TcxFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiff (*.tiff; *.tif)|*.tiff;*.tif.
        /// </summary>
        public static string FileFilter_TiffFiles {
            get {
                return ResourceManager.GetString("FileFilter_TiffFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Rate.
        /// </summary>
        public static string HeartRate {
            get {
                return ResourceManager.GetString("HeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.matstroeng.se/quickroute/en/help.
        /// </summary>
        public static string HelpUrl {
            get {
                return ResourceManager.GetString("HelpUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histogram.
        /// </summary>
        public static string Histogram {
            get {
                return ResourceManager.GetString("Histogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to infinite.
        /// </summary>
        public static string Infinite {
            get {
                return ResourceManager.GetString("Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid map image.
        /// </summary>
        public static string InvalidMapImage {
            get {
                return ResourceManager.GetString("InvalidMapImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid route.
        /// </summary>
        public static string InvalidRoute {
            get {
                return ResourceManager.GetString("InvalidRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap {0}.
        /// </summary>
        public static string LapX {
            get {
                return ResourceManager.GetString("LapX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map image file does not exist..
        /// </summary>
        public static string MapImageFileDoesNotExist {
            get {
                return ResourceManager.GetString("MapImageFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map was not published.
        /// </summary>
        public static string MapPublish_FailureTitle {
            get {
                return ResourceManager.GetString("MapPublish_FailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map was published at {0}..
        /// </summary>
        public static string MapPublish_Success {
            get {
                return ResourceManager.GetString("MapPublish_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The map was published.
        /// </summary>
        public static string MapPublish_SuccessTitle {
            get {
                return ResourceManager.GetString("MapPublish_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no valid QuickRoute files specified..
        /// </summary>
        public static string MultipleFileExporterNoValidFiles {
            get {
                return ResourceManager.GetString("MultipleFileExporterNoValidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files do not contain QuickRoute data and could not be included:
        ///
        ///{0}.
        /// </summary>
        public static string MultipleFileExporterSomeInvalidFiles {
            get {
                return ResourceManager.GetString("MultipleFileExporterSomeInvalidFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Gradient.
        /// </summary>
        public static string NewGradient {
            get {
                return ResourceManager.GetString("NewGradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New map.
        /// </summary>
        public static string NewMap {
            get {
                return ResourceManager.GetString("NewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickRoute version {0} is now avaliable..
        /// </summary>
        public static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features in the new version:.
        /// </summary>
        public static string NewVersionFeatures {
            get {
                return ResourceManager.GetString("NewVersionFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [No GPS devices connected].
        /// </summary>
        public static string NoGPSDevicesConnected {
            get {
                return ResourceManager.GetString("NoGPSDevicesConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no GPS devices connected..
        /// </summary>
        public static string NoGPSDevicesConnectedMessageBox {
            get {
                return ResourceManager.GetString("NoGPSDevicesConnectedMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string NorthAbbreviated {
            get {
                return ResourceManager.GetString("NorthAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Google Earth.
        /// </summary>
        public static string OpenInGoogleEarth {
            get {
                return ResourceManager.GetString("OpenInGoogleEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open multiple QuickRoute files in Google Earth.
        /// </summary>
        public static string OpenMultipleFilesInGoogleEarth {
            get {
                return ResourceManager.GetString("OpenMultipleFilesInGoogleEarth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open QuickRoute file.
        /// </summary>
        public static string OpenQuickRouteFileTitle {
            get {
                return ResourceManager.GetString("OpenQuickRouteFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace.
        /// </summary>
        public static string Pace {
            get {
                return ResourceManager.GetString("Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to {0}?.
        /// </summary>
        public static string PromptSaveChanges {
            get {
                return ResourceManager.GetString("PromptSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickRoute.
        /// </summary>
        public static string QuickRoute {
            get {
                return ResourceManager.GetString("QuickRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickRoute data.
        /// </summary>
        public static string QuickRouteKmlData {
            get {
                return ResourceManager.GetString("QuickRouteKmlData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuickRoute session at {0}.
        /// </summary>
        public static string QuickRouteSession {
            get {
                return ResourceManager.GetString("QuickRouteSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replay.
        /// </summary>
        public static string Replay {
            get {
                return ResourceManager.GetString("Replay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ReplayPosition {
            get {
                return ResourceManager.GetString("ReplayPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tail.
        /// </summary>
        public static string ReplayTail {
            get {
                return ResourceManager.GetString("ReplayTail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        public static string Route {
            get {
                return ResourceManager.GetString("Route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The route file does not exist..
        /// </summary>
        public static string RouteFileDoesNotExist {
            get {
                return ResourceManager.GetString("RouteFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no waypoints in the file..
        /// </summary>
        public static string RouteImportError_NoWaypoints {
            get {
                return ResourceManager.GetString("RouteImportError_NoWaypoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no waypoints with times in the file..
        /// </summary>
        public static string RouteImportError_NoWaypointTimes {
            get {
                return ResourceManager.GetString("RouteImportError_NoWaypointTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string RoutePropertyName_Altitude {
            get {
                return ResourceManager.GetString("RoutePropertyName_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude difference (lap).
        /// </summary>
        public static string RoutePropertyName_AltitudeDifference {
            get {
                return ResourceManager.GetString("RoutePropertyName_AltitudeDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude difference (total).
        /// </summary>
        public static string RoutePropertyName_AltitudeDifferenceFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_AltitudeDifferenceFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascent (lap).
        /// </summary>
        public static string RoutePropertyName_Ascent {
            get {
                return ResourceManager.GetString("RoutePropertyName_Ascent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascent (total).
        /// </summary>
        public static string RoutePropertyName_AscentFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_AscentFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average direction deviation (lap).
        /// </summary>
        public static string RoutePropertyName_AverageDirectionDeviationToNextLap {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageDirectionDeviationToNextLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average direction deviation (total).
        /// </summary>
        public static string RoutePropertyName_AverageDirectionDeviationToNextLapFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageDirectionDeviationToNextLapFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average heart rate (lap).
        /// </summary>
        public static string RoutePropertyName_AverageHeartRate {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageHeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average heart rate (total).
        /// </summary>
        public static string RoutePropertyName_AverageHeartRateFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageHeartRateFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average inclination (lap).
        /// </summary>
        public static string RoutePropertyName_AverageInclination {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageInclination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average inclination (total).
        /// </summary>
        public static string RoutePropertyName_AverageInclinationFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageInclinationFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average route pace (lap).
        /// </summary>
        public static string RoutePropertyName_AverageRoutePace {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageRoutePace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average route pace (total).
        /// </summary>
        public static string RoutePropertyName_AverageRoutePaceFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageRoutePaceFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average route speed (lap).
        /// </summary>
        public static string RoutePropertyName_AverageRouteSpeed {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageRouteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average route speed (total).
        /// </summary>
        public static string RoutePropertyName_AverageRouteSpeedFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageRouteSpeedFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average straight line pace (lap).
        /// </summary>
        public static string RoutePropertyName_AverageStraightLinePace {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageStraightLinePace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average straight line pace (total).
        /// </summary>
        public static string RoutePropertyName_AverageStraightLinePaceFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageStraightLinePaceFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average straight line speed (lap).
        /// </summary>
        public static string RoutePropertyName_AverageStraightLineSpeed {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageStraightLineSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average straight line speed (total).
        /// </summary>
        public static string RoutePropertyName_AverageStraightLineSpeedFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_AverageStraightLineSpeedFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle time at end of lap.
        /// </summary>
        public static string RoutePropertyName_CircleTimeAtEndOfSpan {
            get {
                return ResourceManager.GetString("RoutePropertyName_CircleTimeAtEndOfSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of circle times at end of each lap.
        /// </summary>
        public static string RoutePropertyName_CircleTimeAtEndOfSpanFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_CircleTimeAtEndOfSpanFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle time at start of lap.
        /// </summary>
        public static string RoutePropertyName_CircleTimeAtStartOfSpan {
            get {
                return ResourceManager.GetString("RoutePropertyName_CircleTimeAtStartOfSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of circle times at start of each lap.
        /// </summary>
        public static string RoutePropertyName_CircleTimeAtStartOfSpanFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_CircleTimeAtStartOfSpanFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward circle time.
        /// </summary>
        public static string RoutePropertyName_CircleTimeBackward {
            get {
                return ResourceManager.GetString("RoutePropertyName_CircleTimeBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward circle time.
        /// </summary>
        public static string RoutePropertyName_CircleTimeForward {
            get {
                return ResourceManager.GetString("RoutePropertyName_CircleTimeForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent (lap).
        /// </summary>
        public static string RoutePropertyName_Descent {
            get {
                return ResourceManager.GetString("RoutePropertyName_Descent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent (total).
        /// </summary>
        public static string RoutePropertyName_DescentFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_DescentFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string RoutePropertyName_Direction {
            get {
                return ResourceManager.GetString("RoutePropertyName_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction deviation.
        /// </summary>
        public static string RoutePropertyName_DirectionDeviationToNextLap {
            get {
                return ResourceManager.GetString("RoutePropertyName_DirectionDeviationToNextLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (lap).
        /// </summary>
        public static string RoutePropertyName_ElapsedTime {
            get {
                return ResourceManager.GetString("RoutePropertyName_ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (total).
        /// </summary>
        public static string RoutePropertyName_ElapsedTimeFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_ElapsedTimeFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart rate.
        /// </summary>
        public static string RoutePropertyName_HeartRate {
            get {
                return ResourceManager.GetString("RoutePropertyName_HeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image X position.
        /// </summary>
        public static string RoutePropertyName_ImageX {
            get {
                return ResourceManager.GetString("RoutePropertyName_ImageX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Y position.
        /// </summary>
        public static string RoutePropertyName_ImageY {
            get {
                return ResourceManager.GetString("RoutePropertyName_ImageY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclination.
        /// </summary>
        public static string RoutePropertyName_Inclination {
            get {
                return ResourceManager.GetString("RoutePropertyName_Inclination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap number.
        /// </summary>
        public static string RoutePropertyName_LapNumber {
            get {
                return ResourceManager.GetString("RoutePropertyName_LapNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string RoutePropertyName_Latitude {
            get {
                return ResourceManager.GetString("RoutePropertyName_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string RoutePropertyName_Location {
            get {
                return ResourceManager.GetString("RoutePropertyName_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string RoutePropertyName_Longitude {
            get {
                return ResourceManager.GetString("RoutePropertyName_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum heart rate (lap).
        /// </summary>
        public static string RoutePropertyName_MaxHeartRate {
            get {
                return ResourceManager.GetString("RoutePropertyName_MaxHeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum heart rate (total).
        /// </summary>
        public static string RoutePropertyName_MaxHeartRateFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_MaxHeartRateFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum heart rate (lap).
        /// </summary>
        public static string RoutePropertyName_MinHeartRate {
            get {
                return ResourceManager.GetString("RoutePropertyName_MinHeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum heart rate (total).
        /// </summary>
        public static string RoutePropertyName_MinHeartRateFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_MinHeartRateFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace.
        /// </summary>
        public static string RoutePropertyName_Pace {
            get {
                return ResourceManager.GetString("RoutePropertyName_Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route distance (lap).
        /// </summary>
        public static string RoutePropertyName_RouteDistance {
            get {
                return ResourceManager.GetString("RoutePropertyName_RouteDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route distance (total).
        /// </summary>
        public static string RoutePropertyName_RouteDistanceFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_RouteDistanceFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between the route and the straight line distance (lap).
        /// </summary>
        public static string RoutePropertyName_RouteToStraightLine {
            get {
                return ResourceManager.GetString("RoutePropertyName_RouteToStraightLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between the route and the straight line distance (total).
        /// </summary>
        public static string RoutePropertyName_RouteToStraightLineFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_RouteToStraightLineFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string RoutePropertyName_Speed {
            get {
                return ResourceManager.GetString("RoutePropertyName_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight line distance (lap).
        /// </summary>
        public static string RoutePropertyName_StraightLineDistance {
            get {
                return ResourceManager.GetString("RoutePropertyName_StraightLineDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight line distance (total).
        /// </summary>
        public static string RoutePropertyName_StraightLineDistanceFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyName_StraightLineDistanceFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of day.
        /// </summary>
        public static string RoutePropertyName_Time {
            get {
                return ResourceManager.GetString("RoutePropertyName_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude: {0} masl.
        /// </summary>
        public static string RoutePropertyNameAndValue_Altitude {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude difference (lap): {0} m.
        /// </summary>
        public static string RoutePropertyNameAndValue_AltitudeDifference {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AltitudeDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude difference (total): {0} m.
        /// </summary>
        public static string RoutePropertyNameAndValue_AltitudeDifferenceFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AltitudeDifferenceFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascent (lap): {0} m.
        /// </summary>
        public static string RoutePropertyNameAndValue_Ascent {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Ascent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascent (total): {0} m.
        /// </summary>
        public static string RoutePropertyNameAndValue_AscentFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AscentFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average direction deviation (lap): {0}°.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageDirectionDeviationToNextLap {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageDirectionDeviationToNextLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average direction deviation (total): {0}°.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageDirectionDeviationToNextLapFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageDirectionDeviationToNextLapFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average heart rate (lap): {0} bpm.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageHeartRate {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageHeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average heart rate (total): {0} bpm.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageHeartRateFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageHeartRateFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average inclination (lap): {0}°.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageInclination {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageInclination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average inclination (total): {0}°.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageInclinationFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageInclinationFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average route pace (lap): {0} min/km.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageRoutePace {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageRoutePace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average route pace (total): {0} min/km.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageRoutePaceFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageRoutePaceFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average route speed (lap): {0} km/h.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageRouteSpeed {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageRouteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average route speed (total): {0} km/h.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageRouteSpeedFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageRouteSpeedFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average straight line pace (lap): {0} min/km.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageStraightLinePace {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageStraightLinePace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average straight line pace (total): {0} min/km.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageStraightLinePaceFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageStraightLinePaceFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average straight line speed (lap): {0} km/h.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageStraightLineSpeed {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageStraightLineSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average straight line speed (total): {0} km/h.
        /// </summary>
        public static string RoutePropertyNameAndValue_AverageStraightLineSpeedFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_AverageStraightLineSpeedFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle time at end of lap: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_CircleTimeAtEndOfSpan {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_CircleTimeAtEndOfSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of circle times at end of each lap: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_CircleTimeAtEndOfSpanFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_CircleTimeAtEndOfSpanFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle time at start of lap: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_CircleTimeAtStartOfSpan {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_CircleTimeAtStartOfSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of circle times at start of each lap: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_CircleTimeAtStartOfSpanFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_CircleTimeAtStartOfSpanFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward circle time: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_CircleTimeBackward {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_CircleTimeBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward circle time: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_CircleTimeForward {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_CircleTimeForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent (lap): {0} m.
        /// </summary>
        public static string RoutePropertyNameAndValue_Descent {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Descent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descent (total): {0} m.
        /// </summary>
        public static string RoutePropertyNameAndValue_DescentFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_DescentFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction: {0}°.
        /// </summary>
        public static string RoutePropertyNameAndValue_Direction {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction deviation: {0}°.
        /// </summary>
        public static string RoutePropertyNameAndValue_DirectionDeviationToNextLap {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_DirectionDeviationToNextLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (lap): {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_ElapsedTime {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_ElapsedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time (total): {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_ElapsedTimeFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_ElapsedTimeFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart rate: {0} bpm.
        /// </summary>
        public static string RoutePropertyNameAndValue_HeartRate {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_HeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image X position: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_ImageX {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_ImageX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Y position: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_ImageY {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_ImageY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclination: {0}°.
        /// </summary>
        public static string RoutePropertyNameAndValue_Inclination {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Inclination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap number: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_LapNumber {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_LapNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_Latitude {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_Location {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_Longitude {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum heart rate (lap): {0} bpm.
        /// </summary>
        public static string RoutePropertyNameAndValue_MaxHeartRate {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_MaxHeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum heart rate (total): {0} bpm.
        /// </summary>
        public static string RoutePropertyNameAndValue_MaxHeartRateFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_MaxHeartRateFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum heart rate (lap): {0} bpm.
        /// </summary>
        public static string RoutePropertyNameAndValue_MinHeartRate {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_MinHeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum heart rate (total): {0} bpm.
        /// </summary>
        public static string RoutePropertyNameAndValue_MinHeartRateFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_MinHeartRateFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pace: {0} min/km.
        /// </summary>
        public static string RoutePropertyNameAndValue_Pace {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route distance (lap): {0} m.
        /// </summary>
        public static string RoutePropertyNameAndValue_RouteDistance {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_RouteDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route distance (total): {0} m.
        /// </summary>
        public static string RoutePropertyNameAndValue_RouteDistanceFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_RouteDistanceFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between the route and the straight line distance (lap): {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_RouteToStraightLine {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_RouteToStraightLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difference between the route and the straight line distance (total): {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_RouteToStraightLineFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_RouteToStraightLineFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed: {0} km/h.
        /// </summary>
        public static string RoutePropertyNameAndValue_Speed {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight line distance (lap): {0} m.
        /// </summary>
        public static string RoutePropertyNameAndValue_StraightLineDistance {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_StraightLineDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight line distance (total): {0} m.
        /// </summary>
        public static string RoutePropertyNameAndValue_StraightLineDistanceFromStart {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_StraightLineDistanceFromStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of day: {0}.
        /// </summary>
        public static string RoutePropertyNameAndValue_Time {
            get {
                return ResourceManager.GetString("RoutePropertyNameAndValue_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes.
        /// </summary>
        public static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route segment {0}.
        /// </summary>
        public static string RouteSegmentX {
            get {
                return ResourceManager.GetString("RouteSegmentX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save QuickRoute File As.
        /// </summary>
        public static string SaveAsTitle {
            get {
                return ResourceManager.GetString("SaveAsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select columns.
        /// </summary>
        public static string SelectLapInfoColumns {
            get {
                return ResourceManager.GetString("SelectLapInfoColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select map image file.
        /// </summary>
        public static string SelectMapImageFile {
            get {
                return ResourceManager.GetString("SelectMapImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select information.
        /// </summary>
        public static string SelectMomentaneousInfoProperties {
            get {
                return ResourceManager.GetString("SelectMomentaneousInfoProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select route file.
        /// </summary>
        public static string SelectRouteFile {
            get {
                return ResourceManager.GetString("SelectRouteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1} pixels.
        /// </summary>
        public static string SizeInPixels {
            get {
                return ResourceManager.GetString("SizeInPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoothing interval for {0}.
        /// </summary>
        public static string SmoothingIntervalForX {
            get {
                return ResourceManager.GetString("SmoothingIntervalForX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SouthAbbreviated {
            get {
                return ResourceManager.GetString("SouthAbbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language change will take effect next time QuickRoute is started..
        /// </summary>
        public static string UICultureChangeTakesEffectAtNextRestart {
            get {
                return ResourceManager.GetString("UICultureChangeTakesEffectAtNextRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occured..
        /// </summary>
        public static string UnexpectedExceptionMessage {
            get {
                return ResourceManager.GetString("UnexpectedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to masl.
        /// </summary>
        public static string Unit_Altitude {
            get {
                return ResourceManager.GetString("Unit_Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to °.
        /// </summary>
        public static string Unit_Direction {
            get {
                return ResourceManager.GetString("Unit_Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string Unit_Distance {
            get {
                return ResourceManager.GetString("Unit_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bpm.
        /// </summary>
        public static string Unit_HeartRate {
            get {
                return ResourceManager.GetString("Unit_HeartRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min/km.
        /// </summary>
        public static string Unit_Pace {
            get {
                return ResourceManager.GetString("Unit_Pace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        public static string Unit_Speed {
            get {
                return ResourceManager.GetString("Unit_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file format of {0} is not recognized..
        /// </summary>
        public static string UnrecognizedFileFormat {
            get {
                return ResourceManager.GetString("UnrecognizedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled {0}.
        /// </summary>
        public static string UntitledX {
            get {
                return ResourceManager.GetString("UntitledX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to matstroeng.se/quickroute/en.
        /// </summary>
        public static string WebsiteShortUrl {
            get {
                return ResourceManager.GetString("WebsiteShortUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.matstroeng.se/quickroute/en.
        /// </summary>
        public static string WebsiteUrl {
            get {
                return ResourceManager.GetString("WebsiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string WestAbbreviated {
            get {
                return ResourceManager.GetString("WestAbbreviated", resourceCulture);
            }
        }
    }
}
