//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace QuickRoute.Publishers.DOMAPublisher.DOMA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DOMAServiceBinding", Namespace="http://www.matstroeng.se/doma")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Category))]
    public partial class DOMAService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PublishMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback PublishPreUploadedMapOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadPartialFileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllMapsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllCategoriesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConnectOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DOMAService() {
            this.Url = global::QuickRoute.Publishers.DOMAPublisher.Properties.Settings.Default.QuickRoute_Publishers_DOMAPublisher_DOMA_DOMAService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PublishMapCompletedEventHandler PublishMapCompleted;
        
        /// <remarks/>
        public event PublishPreUploadedMapCompletedEventHandler PublishPreUploadedMapCompleted;
        
        /// <remarks/>
        public event UploadPartialFileCompletedEventHandler UploadPartialFileCompleted;
        
        /// <remarks/>
        public event GetAllMapsCompletedEventHandler GetAllMapsCompleted;
        
        /// <remarks/>
        public event GetAllCategoriesCompletedEventHandler GetAllCategoriesCompleted;
        
        /// <remarks/>
        public event ConnectCompletedEventHandler ConnectCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/domadev/webservice.php/PublishMap", RequestNamespace="http://www.matstroeng.se/doma", ResponseNamespace="http://www.matstroeng.se/doma")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public PublishMapResponse PublishMap(PublishMapRequest request) {
            object[] results = this.Invoke("PublishMap", new object[] {
                        request});
            return ((PublishMapResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PublishMapAsync(PublishMapRequest request) {
            this.PublishMapAsync(request, null);
        }
        
        /// <remarks/>
        public void PublishMapAsync(PublishMapRequest request, object userState) {
            if ((this.PublishMapOperationCompleted == null)) {
                this.PublishMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublishMapOperationCompleted);
            }
            this.InvokeAsync("PublishMap", new object[] {
                        request}, this.PublishMapOperationCompleted, userState);
        }
        
        private void OnPublishMapOperationCompleted(object arg) {
            if ((this.PublishMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublishMapCompleted(this, new PublishMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/domadev/webservice.php/PublishPreUploadedMap", RequestNamespace="http://www.matstroeng.se/doma", ResponseNamespace="http://www.matstroeng.se/doma")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public PublishPreUploadedMapResponse PublishPreUploadedMap(PublishPreUploadedMapRequest request) {
            object[] results = this.Invoke("PublishPreUploadedMap", new object[] {
                        request});
            return ((PublishPreUploadedMapResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PublishPreUploadedMapAsync(PublishPreUploadedMapRequest request) {
            this.PublishPreUploadedMapAsync(request, null);
        }
        
        /// <remarks/>
        public void PublishPreUploadedMapAsync(PublishPreUploadedMapRequest request, object userState) {
            if ((this.PublishPreUploadedMapOperationCompleted == null)) {
                this.PublishPreUploadedMapOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPublishPreUploadedMapOperationCompleted);
            }
            this.InvokeAsync("PublishPreUploadedMap", new object[] {
                        request}, this.PublishPreUploadedMapOperationCompleted, userState);
        }
        
        private void OnPublishPreUploadedMapOperationCompleted(object arg) {
            if ((this.PublishPreUploadedMapCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PublishPreUploadedMapCompleted(this, new PublishPreUploadedMapCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/domadev/webservice.php/UploadPartialFile", RequestNamespace="http://www.matstroeng.se/doma", ResponseNamespace="http://www.matstroeng.se/doma")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public UploadPartialFileResponse UploadPartialFile(UploadPartialFileRequest request) {
            object[] results = this.Invoke("UploadPartialFile", new object[] {
                        request});
            return ((UploadPartialFileResponse)(results[0]));
        }
        
        /// <remarks/>
        public void UploadPartialFileAsync(UploadPartialFileRequest request) {
            this.UploadPartialFileAsync(request, null);
        }
        
        /// <remarks/>
        public void UploadPartialFileAsync(UploadPartialFileRequest request, object userState) {
            if ((this.UploadPartialFileOperationCompleted == null)) {
                this.UploadPartialFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadPartialFileOperationCompleted);
            }
            this.InvokeAsync("UploadPartialFile", new object[] {
                        request}, this.UploadPartialFileOperationCompleted, userState);
        }
        
        private void OnUploadPartialFileOperationCompleted(object arg) {
            if ((this.UploadPartialFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadPartialFileCompleted(this, new UploadPartialFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/domadev/webservice.php/GetAllMaps", RequestNamespace="http://www.matstroeng.se/doma", ResponseNamespace="http://www.matstroeng.se/doma")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public GetAllMapsResponse GetAllMaps(GetAllMapsRequest request) {
            object[] results = this.Invoke("GetAllMaps", new object[] {
                        request});
            return ((GetAllMapsResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllMapsAsync(GetAllMapsRequest request) {
            this.GetAllMapsAsync(request, null);
        }
        
        /// <remarks/>
        public void GetAllMapsAsync(GetAllMapsRequest request, object userState) {
            if ((this.GetAllMapsOperationCompleted == null)) {
                this.GetAllMapsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllMapsOperationCompleted);
            }
            this.InvokeAsync("GetAllMaps", new object[] {
                        request}, this.GetAllMapsOperationCompleted, userState);
        }
        
        private void OnGetAllMapsOperationCompleted(object arg) {
            if ((this.GetAllMapsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllMapsCompleted(this, new GetAllMapsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/domadev/webservice.php/GetAllCategories", RequestNamespace="http://www.matstroeng.se/doma", ResponseNamespace="http://www.matstroeng.se/doma")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public GetAllCategoriesResponse GetAllCategories(GetAllCategoriesRequest request) {
            object[] results = this.Invoke("GetAllCategories", new object[] {
                        request});
            return ((GetAllCategoriesResponse)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllCategoriesAsync(GetAllCategoriesRequest request) {
            this.GetAllCategoriesAsync(request, null);
        }
        
        /// <remarks/>
        public void GetAllCategoriesAsync(GetAllCategoriesRequest request, object userState) {
            if ((this.GetAllCategoriesOperationCompleted == null)) {
                this.GetAllCategoriesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCategoriesOperationCompleted);
            }
            this.InvokeAsync("GetAllCategories", new object[] {
                        request}, this.GetAllCategoriesOperationCompleted, userState);
        }
        
        private void OnGetAllCategoriesOperationCompleted(object arg) {
            if ((this.GetAllCategoriesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllCategoriesCompleted(this, new GetAllCategoriesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://localhost/domadev/webservice.php/Connect", RequestNamespace="http://www.matstroeng.se/doma", ResponseNamespace="http://www.matstroeng.se/doma")]
        [return: System.Xml.Serialization.SoapElementAttribute("response")]
        public ConnectResponse Connect(ConnectRequest request) {
            object[] results = this.Invoke("Connect", new object[] {
                        request});
            return ((ConnectResponse)(results[0]));
        }
        
        /// <remarks/>
        public void ConnectAsync(ConnectRequest request) {
            this.ConnectAsync(request, null);
        }
        
        /// <remarks/>
        public void ConnectAsync(ConnectRequest request, object userState) {
            if ((this.ConnectOperationCompleted == null)) {
                this.ConnectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConnectOperationCompleted);
            }
            this.InvokeAsync("Connect", new object[] {
                        request}, this.ConnectOperationCompleted, userState);
        }
        
        private void OnConnectOperationCompleted(object arg) {
            if ((this.ConnectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConnectCompleted(this, new ConnectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class PublishMapRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private MapInfo mapInfoField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo MapInfo {
            get {
                return this.mapInfoField;
            }
            set {
                this.mapInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class MapInfo {
        
        private int idField;
        
        private int userIDField;
        
        private int categoryIDField;
        
        private System.DateTime dateField;
        
        private string nameField;
        
        private string organiserField;
        
        private string countryField;
        
        private string disciplineField;
        
        private string relayLegField;
        
        private string mapNameField;
        
        private string resultListUrlField;
        
        private string commentField;
        
        private byte[] mapImageDataField;
        
        private string mapImageFileExtensionField;
        
        private byte[] blankMapImageDataField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public int CategoryID {
            get {
                return this.categoryIDField;
            }
            set {
                this.categoryIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Organiser {
            get {
                return this.organiserField;
            }
            set {
                this.organiserField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Discipline {
            get {
                return this.disciplineField;
            }
            set {
                this.disciplineField = value;
            }
        }
        
        /// <remarks/>
        public string RelayLeg {
            get {
                return this.relayLegField;
            }
            set {
                this.relayLegField = value;
            }
        }
        
        /// <remarks/>
        public string MapName {
            get {
                return this.mapNameField;
            }
            set {
                this.mapNameField = value;
            }
        }
        
        /// <remarks/>
        public string ResultListUrl {
            get {
                return this.resultListUrlField;
            }
            set {
                this.resultListUrlField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] MapImageData {
            get {
                return this.mapImageDataField;
            }
            set {
                this.mapImageDataField = value;
            }
        }
        
        /// <remarks/>
        public string MapImageFileExtension {
            get {
                return this.mapImageFileExtensionField;
            }
            set {
                this.mapImageFileExtensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] BlankMapImageData {
            get {
                return this.blankMapImageDataField;
            }
            set {
                this.blankMapImageDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class ConnectResponse {
        
        private bool successField;
        
        private string errorMessageField;
        
        private string versionField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class ConnectRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class Category {
        
        private int idField;
        
        private int userIDField;
        
        private string nameField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class GetAllCategoriesResponse {
        
        private bool successField;
        
        private string errorMessageField;
        
        private Category[] categoriesField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public Category[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class GetAllCategoriesRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class GetAllMapsResponse {
        
        private bool successField;
        
        private string errorMessageField;
        
        private MapInfo[] mapsField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo[] Maps {
            get {
                return this.mapsField;
            }
            set {
                this.mapsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class GetAllMapsRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class UploadPartialFileResponse {
        
        private bool successField;
        
        private string errorMessageField;
        
        private string fileNameField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class UploadPartialFileRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private string fileNameField;
        
        private byte[] dataField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")]
        public byte[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class PublishPreUploadedMapResponse {
        
        private bool successField;
        
        private string errorMessageField;
        
        private string uRLField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class PublishPreUploadedMapRequest {
        
        private string usernameField;
        
        private string passwordField;
        
        private MapInfo mapInfoField;
        
        private string preUploadedMapImageFileNameField;
        
        private string preUploadedBlankMapImageFileNameField;
        
        private string preUploadedThumbnailImageFileNameField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public MapInfo MapInfo {
            get {
                return this.mapInfoField;
            }
            set {
                this.mapInfoField = value;
            }
        }
        
        /// <remarks/>
        public string PreUploadedMapImageFileName {
            get {
                return this.preUploadedMapImageFileNameField;
            }
            set {
                this.preUploadedMapImageFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string PreUploadedBlankMapImageFileName {
            get {
                return this.preUploadedBlankMapImageFileNameField;
            }
            set {
                this.preUploadedBlankMapImageFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string PreUploadedThumbnailImageFileName {
            get {
                return this.preUploadedThumbnailImageFileNameField;
            }
            set {
                this.preUploadedThumbnailImageFileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://www.matstroeng.se/doma")]
    public partial class PublishMapResponse {
        
        private bool successField;
        
        private string errorMessageField;
        
        private string uRLField;
        
        /// <remarks/>
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PublishMapCompletedEventHandler(object sender, PublishMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PublishMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PublishMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PublishMapResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PublishMapResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PublishPreUploadedMapCompletedEventHandler(object sender, PublishPreUploadedMapCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PublishPreUploadedMapCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PublishPreUploadedMapCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PublishPreUploadedMapResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PublishPreUploadedMapResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UploadPartialFileCompletedEventHandler(object sender, UploadPartialFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadPartialFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadPartialFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UploadPartialFileResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UploadPartialFileResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllMapsCompletedEventHandler(object sender, GetAllMapsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllMapsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllMapsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAllMapsResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAllMapsResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetAllCategoriesCompletedEventHandler(object sender, GetAllCategoriesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllCategoriesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllCategoriesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetAllCategoriesResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetAllCategoriesResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ConnectCompletedEventHandler(object sender, ConnectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConnectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConnectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ConnectResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ConnectResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591